### PR TITLE
Make `ProgramError` & `CairoRunError` implement `PartialEq`

### PR DESCRIPTION
**Pull request by fmoletta**
This PR aims to make the CairoRunError more user-friendly by making sure it implements PartialEq

### CODE REVIEW

**Review by Oppen — APPROVED** [review]

**Review by Jrigada — APPROVED** [review]

**Comment by tdelabro** [comment]
Hey,
Just saw this one and it will conflict with #751 
The reason is `Box<dyn Error>` does not implement `PartialEq` and we cannot use `Box<dyn Error + PartialEq>` because lot of error types don't implement `PartialEq`.
You will find multiple online threads about this specific issue and how most projects opt for not implementing `PartialEq` on their error types. Instead, they use `assert_matches` for tests.
 
@hurrikaanig  is coming up with a PR that will remove PartialEq on the different Errors types in the project and migrate all tests from `assert!` to `assert_matches!`

So please don't merge  :)

**Comment by Oppen** [comment]
@tdelabro this sounds like a sensible request. @fmoletta do you think we can close this one?
